# Generated by Django 5.1.4 on 2024-12-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_item_image_remove_photo_title_photo_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.item'),
        ),
    ]
